### ISSUE TITLE
Make docker images available in Docker Hub

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript#240]
It would be awesome to have docker images in Docker hub for both agent and mediator, so it is easy to deploy at backend.

I saw there is a Hyperledger account: https://hub.docker.com/u/hyperledger

**Comment by TimoGlastra** [comment]
what would you assume that's in the agent container? I get the mediator, the other one I'm not so sure about

**Comment by icc-romeu** [comment]
Good point @TimoGlastra. 

On mediator I think it's quite clear it is useful by itself. The current functionality is quite basic but it does the job, nevertheless I would suggest to follow the same path ACA-py does, which is having a REST API in front of the agent. On ACA-py you can choose if you want to start an "agent" or a "mediator". We could do the same.

Maybe this should be in another repository like Aries Cloud Agent Javascript? So anyone willing to use it will just have to download the docker image.

**Comment by icc-romeu** [comment]
Just in case it helps, I am using a mediator with this docker compose file. 

It is quite convenient to deploy this way. You just have to setup the url were the container will run, and that's it:

```
version: '3'
services:
  mediator01:
    image: iccromeu/aries-framework-javascript
    container_name: mediator01
    command: yarn prod:start
    environment:
      - AGENT_ENDPOINT=${AGENT_ENDPOINT:-theURL:3001}
      - AGENT_HOST=theURL
      - AGENT_PORT=3001
      - AGENT_LABEL=RoutingMediator01
      - WALLET_NAME=mediator01
      - WALLET_KEY=0000000000000000000000000Mediator01
      - PUBLIC_DID=DtWRdd6C5dN5vpcN6XRAvu
      - PUBLIC_DID_SEED=00000000000000000000000Forward01
    ports:
      - 3001:3001
```
